version: '3.8'

services:

    # PHP Web Application Service
    web:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-app
        volumes:
            - ./workspace:/var/www/html
        ports:
            - "80:80"
        depends_on:
            - db

    # MySQL Database Service
    db:
        image: mysql:8.0
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: cde3bgt5_root # Root password
            MYSQL_USER: ncwww # Custom MySQL user
            MYSQL_PASSWORD: cde3bgt5 # Password for custom MySQL user
            MYSQL_DATABASE: message_board # Database to create at startup
        volumes:
            - db_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password # Ensures compatibility with older MySQL clients

 

# Named volume for persistent MySQL data
volumes:
    db_data:
