version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-app
        volumes:
            - ./workspace:/var/www/html
        ports:
            - "80:80"
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: cde3bgt5_root
            MYSQL_USER: ncwww
            MYSQL_PASSWORD: cde3bgt5
            MYSQL_DATABASE: employees